// @flow

const defaultImages = {
  logo: require('../images/logo.png'),
  logoLemon: require('../images/logo_lemon.png'),
  back: require('../images/back.png'),
  headerBack: require('../images/header_back.png'),
  forward: require('../images/forward.png'),
  myFormsIcon: require('../images/my_forms_icon.png'),
  mySanitationIcon: require('../images/sanitation_icon.png'),
  radioSelected: require('../images/radio_yes.png'),
  radioUnSelected: require('../images/radio_no.png'),
  home: require('../images/home.png'),
  upload: require('../images/upload.png'),
  assignedAudits: require('../images/assigned_audits_icon.png'),
  nextGrey: require('../images/next_icon_grey.png'),
  module11: require('../images/module_11_icon.png'),
};

const eagle = {
  logo: null,
  logoLemon: null,
  back: require('../images/eagle/back.png'),
  headerBack: require('../images/eagle/header_back.png'),
  forward: require('../images/eagle/forward.png'),
  myFormsIcon: require('../images/eagle/my_forms_icon.png'),
  mySanitationIcon: require('../images/eagle/sanitation_icon.png'),
  radioSelected: require('../images/eagle/radio_yes.png'),
  radioUnSelected: require('../images/eagle/radio_no.png'),
  upload: require('../images/eagle/upload.png'),
  assignedAudits: require('../images/eagle/assigned_audits_icon.png'),
  nextGrey: require('../images/eagle/next_icon_grey.png'),
  module11: require('../images/eagle/module_11_icon.png'),
  assignedAudit: require('../images/eagle/assigned_audit_icon.png'),
  attachDocument: require('../images/eagle/attach_document_button.png'),
  correctiveTrue: require('../images/eagle/corrective_action_true.png'),
  correctiveFalse: require('../images/eagle/corrective_action_false.png'),
  deskAudit: require('../images/eagle/desk_audit_icon.png'),
  homeBackground: require('../images/eagle/home_page_background.png'),
  inprogressAudit: require('../images/eagle/inprogress_icon.png'),
  myStats: require('../images/eagle/my_stats_icon.png'),
  pendingAudit: require('../images/eagle/pending_audits_icon.png'),
  eagleLogo: require('../images/eagle/login_eagle.png'),
  eagleLoginLogo: require('../images/eagle/eagle_login_logo.png'),
  rememberMeSelected: require('../images/eagle/remember_me_selected.png'),
  rememberMeUnselected: require('../images/eagle/remember_me_unselected.png'),
  loginBtn: require('../images/eagle/login_button.png'),

  failedAudits: require('../images/eagle/failedaudits_icon.png'),
  heatmap: require('../images/eagle/heatmap_icon.png'),
  percentage: require('../images/eagle/percentage_icon.png'),
  scoresOverTime: require('../images/eagle/scoresover_time_icon.png'),
};

const sqf = {
  logo: null,
  logoLemon: null,
  back: require('../images/sqf/back.png'),
  newAuditBtn: require('../images/sqf/new_audit_button.png'),
  headerBack: require('../images/sqf/header_back.png'),
  forward: require('../images/sqf/forward.png'),
  myFormsIcon: require('../images/sqf/my_forms_icon.png'),
  mySanitationIcon: require('../images/sqf/sanitation_icon.png'),
  radioSelected: require('../images/sqf/module_action_selected.png'),
  radioUnSelected: require('../images/sqf/radio_no.png'),
  upload: require('../images/sqf/upload.png'),
  assignedAudits: require('../images/sqf/assigned_audits_icon.png'),
  nextGrey: require('../images/sqf/next_icon_grey.png'),
  module11: require('../images/sqf/module_11_icon.png'),
  assignedAudit: require('../images/sqf/assigned_audit_icon.png'),
  attachDocument: require('../images/sqf/attach_document_button.png'),
  correctiveTrue: require('../images/sqf/corrective_action_true.png'),
  correctiveFalse: require('../images/sqf/corrective_action_false.png'),
  deskAudit: require('../images/sqf/desk_audit_icon.png'),
  homeBackground: require('../images/sqf/home_page_background.png'),
  inprogressAudit: require('../images/sqf/inprogress_icon.png'),
  myStats: require('../images/sqf/my_stats_icon.png'),
  pendingAudit: require('../images/sqf/pending_audits_icon.png'),
  eagleLogo: require('../images/sqf/login_eagle.png'),
  eagleLoginLogo: require('../images/sqf/sqf_login_background.png'),
  rememberMeSelected: require('../images/sqf/remember_me_selected.png'),
  rememberMeUnselected: require('../images/sqf/remember_me_unselected.png'),
  loginBtn: require('../images/sqf/sqf_login_button.png'),
  signupBtn: require('../images/sqf/sqf_signup_button.png'),

  failedAudits: require('../images/sqf/failedaudits_icon.png'),
  heatmap: require('../images/sqf/heatmap_icon.png'),
  percentage: require('../images/sqf/percentage_icon.png'),
  scoresOverTime: require('../images/sqf/scoresover_time_icon.png'),
};

const mqm = {
  logo: null,
  logoLemon: null,
  back: require('../images/mqm/back.png'),
  headerBack: require('../images/mqm/header_back.png'),
  forward: require('../images/mqm/forward.png'),
  myFormsIcon: require('../images/mqm/my_forms_icon.png'),
  mySanitationIcon: require('../images/mqm/sanitation_icon.png'),
  radioSelected: require('../images/mqm/radio_yes.png'),
  radioUnSelected: require('../images/mqm/radio_no.png'),
  upload: require('../images/mqm/upload.png'),
  assignedAudits: require('../images/mqm/signature_icon.png'),
  selectQuestion: require('../images/mqm/select_question_icon.png'),
  signature_icon: require('../images/mqm/signature_icon.png'),
  nextGrey: require('../images/eagle/next_icon_grey.png'),
  nextBlue: require('../images/mqm/next_icon_blue.png'),
  module11: require('../images/mqm/module_11_icon.png'),
  pass: require('../images/mqm/pass.png'),
  fail: require('../images/mqm/fail.png'),
};

export default {
  defaultImages,
  eagle,
  mqm,
  sqf,
};
